# Frames per second
fps: 60
# Simulation ticks per frame
tpf: 10
# Table width (mm)
width: 1270
# Table length (mm)
height: 2540
# Ball radius (mm)
radius: 28.6
# Friction (mm/s²)
friction: 100
pockets:
  - side: top_left
    diameter: 130
  - side: top_right
    diameter: 130
  - side: bottom_left
    diameter: 130
  - side: bottom_right
    diameter: 130
  - side: left
    diameter: 140
    pos: 1270
  - side: right
    diameter: 140
    pos: 1270
balls:
  - name: "ball_1"          # Unique identifier
    pos: [300, 300]         # Initial ball position ([x, y])
    vel: [0, 00]            # Initial ball velocity ([x, y])
    col: [0xfc, 0xea, 0x23] # Ball colour in RGB format ([r, g, b])
  - name: "ball_2"
    pos: [600, 600]
    vel: [0, 0]
    col: [0xe4, 0x66, 0x15]
  - name: "ball_3"
    pos: [600, 1300]
    vel: [0, 0]
    col: [0, 0, 0]
actions:
  - ball: "ball_1"          # Name of the ball to be played
    push:                   # Push a ball into a direction
      ball: "ball_3"        # Name of the ball to be pushed
      dest: [1270, 2540]    # Point the pushed ball should move towards
      vel: 2000             # Initial velocity of the played ball
  - ball: "ball_2"
    push:
      ball: "ball_1"
      dest: [0, 2540]
      vel: 800