fps: 60
width: 1270
height: 2540
radius: 28.6
friction: 100
pockets:
  - side: top_left
    diameter: 130
  - side: top_right
    diameter: 130
  - side: bottom_left
    diameter: 130
  - side: bottom_right
    diameter: 130
  - side: left
    diameter: 140
    pos: 1270
  - side: right
    diameter: 140
    pos: 1270
balls:
  - name: "ball_1"
    pos: [300, 300]
    vel: [0, 00]
    col: [0xfc, 0xea, 0x23]
  - name: "ball_2"
    pos: [600, 600]
    vel: [0, 0]
    col: [0xe4, 0x66, 0x15]
  - name: "ball_3"
    pos: [600, 1300]
    vel: [0, 0]
    col: [0, 0, 0]
actions:
  - ball: "ball_1"
    bump:
      ball: "ball_3"
      dest: [1270, 1270]
      vel: 2000
  - ball: "ball_2"
    bump:
      ball: "ball_1"
      dest: [1250, 0]
      vel: 800